global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          group: 'canary'

  - job_name: 'otelcollector'
    static_configs:
      - targets: ['collector:8889']
        labels:
          group: 'prod'
          